In [1]:
import numpy as np

In [3]:
arr = np.arange(0,10)
arr



arr1 = arr + arr
arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arrr1 = arr - arr

In [6]:
print(arrr1)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
arrr1/arrr1

<ipython-input-8-0ef0ef20f2e5>:1: RuntimeWarning: invalid value encountered in true_divide
  arrr1/arrr1


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [9]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [11]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
np.log(arr)

<ipython-input-13-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])