In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(arr)
arr[0:5] = 100


arr

[ 0  1  2  3  4  5  6  7  8  9 10]


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr[0:6]


slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:] =(99)


slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_2d[1]

array([4, 5, 6])

In [16]:
arr_2d[1][0]

4

In [17]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [18]:
arr2d = np.zeros((10,10))

In [19]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
arr_length = arr2d.shape[1]
print(arr_length)

10


In [21]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [30]:
arr2d[-3:2:-1,-5::1]

array([[7., 7., 7., 7., 7.],
       [6., 6., 6., 6., 6.],
       [5., 5., 5., 5., 5.],
       [4., 4., 4., 4., 4.],
       [3., 3., 3., 3., 3.]])

In [41]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
bool_arr = arr > 4

In [44]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [45]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a00rr2=np.random.randint(1,10,(7,10))

In [27]:
a00rr2

array([[4, 1, 7, 6, 8, 9, 4, 8, 3, 9],
       [4, 8, 8, 2, 2, 5, 1, 7, 2, 6],
       [7, 7, 4, 7, 7, 3, 8, 2, 9, 8],
       [4, 7, 4, 2, 4, 9, 3, 1, 1, 3],
       [3, 9, 3, 9, 7, 4, 8, 1, 9, 5],
       [8, 5, 2, 7, 2, 5, 6, 7, 4, 4],
       [2, 6, 3, 4, 7, 9, 4, 6, 5, 7]])

In [31]:
a00rr2[-3:2:-1,-5::1]

array([[4, 8, 1, 9, 5],
       [9, 3, 1, 1, 3]])