In [1]:
conda install numpy

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\users\dell\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    asttokens-2.0.5            |     pyhd3eb1b0_0          20 KB
    attrs-24.2.0               |   py38haa95532_0         153 KB
    babel-2.11.0               |   py38haa95532_0         6.8 MB
    beautifulsoup4-4.12.3      |   py38haa95532_0         214 KB
    ca-certificates-2025.7.15  |       haa95532_0         127 KB
    charset-normalizer-3.3.2   |     pyhd3eb1b0_0          44 KB
    comm-0.2.1                 |   py38haa95532_0          15 KB
    debugpy-1.6.7              


The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::anaconda-client==1.7.2=py38_0
  - defaults/win-64::anaconda==custom=py38_1
  - defaults/win-64::anaconda-navigator==2.4.2=py38haa95532_0
  - defaults/noarch::anaconda-project==0.9.1=pyhd3eb1b0_1
  - defaults/win-64::astropy==4.2.1=py38h2bbff1b_1
  - defaults/win-64::bkcharts==0.2=py38_0
  - defaults/noarch::black==19.10b0=py_0
  - defaults/noarch::bleach==3.3.0=pyhd3eb1b0_0
  - defaults/win-64::bokeh==2.3.2=py38haa95532_0
  - defaults/win-64::bottleneck==1.3.2=py38h2a96729_1
  - defaults/win-64::conda==23.3.1=py38haa95532_0
  - defaults/win-64::conda-build==3.23.3=py38haa95532_0
  - defaults/noarch::conda-repo-cli==1.0.4=pyhd3eb1b0_0
  - defaults/noarch::conda-token==0.3.0=pyhd3eb1b0_0
  - defaults/noarch::conda-verify==3.4.2=py_1
  - defaults/noarch::dask==2021.4.0=pyhd3eb1b0_0
  - defaults/win-64::distributed==2021.4.0=py38haa95532_0
  




















 ... (more hidden) ...






notebook-6.4.12      | 4.6 MB    | #5         |  15% 

















jupyterlab-3.5.3     | 4.0 MB    | ###6       |  37% 



















 ... (more hidden) ...











pandas-1.4.4         | 8.6 MB    | ##6        |  26% 











pandas-1.4.4         | 8.6 MB    | ##6        |  27% 

















jupyterlab-3.5.3     | 4.0 MB    | ###6       |  37% 



















 ... (more hidden) ...











pandas-1.4.4         | 8.6 MB    | ##6        |  27% 

















jupyterlab-3.5.3     | 4.0 MB    | ###7       |  37% 



















 ... (more hidden) ...











pandas-1.4.4         | 8.6 MB    | ##7        |  27% 






notebook-6.4.12      | 4.6 MB    | #5         |  16% 

















jupyterlab-3.5.3     | 4.0 MB    | ###7       |  38% 



















 ... (more hidden) ...











pandas-1.4.4         | 8.6 MB    | ##7        |  27% 



















 ... (more hidden) ...

















ju

In [ ]:
import numpy as np

In [3]:
my_list = [1,2,3]
type(my_list)

s = "10"
a = int(s)
print(type(a))

<class 'int'>


In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3,], [1,2,3], [1,2,3]]
my_matrix
print(type(my_matrix))

<class 'list'>


In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [7]:
np.arange(0,2)

array([0, 1])

In [8]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.arange(30,0,-3)

array([30, 27, 24, 21, 18, 15, 12,  9,  6,  3])

In [10]:
np.arange(0,40,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5,9))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.linspace(0,10,endpoint=False)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(10)

array([0.2615394 , 0.18569748, 0.59120867, 0.64139774, 0.85836042,
       0.59235455, 0.49641079, 0.15875446, 0.30270224, 0.90340069])

In [19]:
np.random.rand(8,2)

array([[0.55004325, 0.38659027],
       [0.52394341, 0.85919351],
       [0.36340305, 0.75718793],
       [0.91506701, 0.64118067],
       [0.1106569 , 0.01622072],
       [0.42975223, 0.33143013],
       [0.17687253, 0.10882235],
       [0.4306561 , 0.83102009]])

In [20]:
np.random.randn(2)

array([ 1.02511382, -1.06825629])

In [21]:
np.random.randn(5,5)

array([[-5.68003995e-01,  2.07413461e-01,  2.97927801e-04,
         1.01217775e+00, -9.63691344e-01],
       [-1.43923398e-01,  7.17052767e-01, -1.41700826e+00,
         4.24862070e-01, -2.59614700e-01],
       [ 3.42567300e-01, -4.19219927e-01, -6.28441365e-01,
        -2.09636914e+00,  5.06445685e-01],
       [ 2.38831241e-01, -1.99717862e+00, -4.66294993e-01,
        -1.10357674e+00,  3.18140887e-01],
       [-6.47829621e-01, -9.35287234e-01,  2.29706744e-01,
         8.76024559e-01,  5.30612118e-01]])

In [22]:
np.random.randint(1,100)

26

In [23]:
np.random.randint(1,100,10)

array([54, 18, 94, 36,  8, 79, 70, 97, 61, 61])

In [24]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([41,  8,  2, 31, 38, 38, 46, 36, 36,  8])

In [1]:
arr1 = np.arange(20)

NameError: name 'np' is not defined

In [28]:
print(arr1.shape)
print(arr1)

NameError: name 'arr1' is not defined

In [27]:
print(arr.shape)

(25,)


In [ ]:
arr1 = arr.reshape(5,5)

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax() #location of the ma

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()